framework:
  - terraform

directory:
  - modules/

soft-fail: true

skip-check:
  - CKV_AWS_130   # Public subnets intentionally assign public IPs
  - CKV2_AWS_11   # VPC flow logs not yet implemented
  - CKV2_AWS_12   # Default security group not managed by module
  - CKV_AWS_18    # S3 access logging requires separate logging bucket
  - CKV_AWS_28    # DynamoDB PITR not needed for lock table
  - CKV_AWS_119   # DynamoDB CMK encryption overkill for lock table
  - CKV2_AWS_61   # S3 lifecycle config planned for later
  - CKV2_AWS_62   # S3 event notifications not needed for state storage
